import { serve } from "https://deno.land/std@0.208.0/http/server.ts"
import { createClient } from "https://esm.sh/@supabase/supabase-js@2"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  try {
    const { 
      symbol, 
      exchange, 
      analysisData,
      insightType = 'COMPREHENSIVE' // COMPREHENSIVE, QUICK, RISK_FOCUSED
    } = await req.json()
    
    if (!symbol || !exchange) {
      return Response.json(
        { error: 'Symbol and exchange are required' },
        { status: 400, headers: corsHeaders }
      )
    }

    const geminiApiKey = Deno.env.get('GEMINI_API_KEY')
    if (!geminiApiKey) {
      return Response.json(
        { 
          success: true, 
          insights: generateFallbackInsights(symbol, analysisData),
          source: 'fallback'
        },
        { headers: corsHeaders }
      )
    }

    console.log(`Generating ${insightType} insights for ${symbol} using Gemini`)

    // Prepare the prompt based on analysis data
    const prompt = buildGeminiPrompt(symbol, exchange, analysisData, insightType)

    // Call Gemini API
    const geminiResponse = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=${geminiApiKey}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [{
            parts: [{ text: prompt }]
          }],
          generationConfig: {
            temperature: 0.3,
            topK: 40,
            topP: 0.95,
            maxOutputTokens: 1024,
          }
        })
      }
    )

    if (!geminiResponse.ok) {
      throw new Error(`Gemini API error: ${geminiResponse.status}`)
    }

    const geminiData = await geminiResponse.json()
    const aiInsights = geminiData.candidates?.[0]?.content?.parts?.[0]?.text

    if (!aiInsights) {
      throw new Error('No insights generated by Gemini')
    }

    // Parse and structure the AI insights
    const structuredInsights = parseGeminiResponse(aiInsights, analysisData)

    console.log(`Successfully generated insights for ${symbol}`)
    return Response.json(
      { 
        success: true, 
        insights: structuredInsights,
        source: 'gemini',
        raw: aiInsights
      },
      { headers: corsHeaders }
    )

  } catch (error) {
    console.error('Gemini insights service error:', error)
    return Response.json(
      { 
        success: true, // Return success with fallback
        insights: generateFallbackInsights(symbol, analysisData),
        source: 'fallback',
        error: error.message
      },
      { headers: corsHeaders }
    )
  }
})

function buildGeminiPrompt(symbol: string, exchange: string, analysisData: any, insightType: string): string {
  const baseContext = `
You are a professional stock analyst providing insights for ${symbol} (${exchange}).

Analysis Data:
- Aggregate Score: ${analysisData?.aggregate_score || 'N/A'}/100
- Recommendation: ${analysisData?.recommendation || 'N/A'}
- Risk Level: ${analysisData?.risk_level || 'N/A'}
- Confidence: ${analysisData?.confidence || 'N/A'}%
- Current Price: $${analysisData?.current_price || 'N/A'}
- Price Change: ${analysisData?.price_change_percent?.toFixed(2) || 'N/A'}%

Fundamental Metrics:
- P/E Ratio: ${analysisData?.fundamental_metrics?.pe_ratio?.toFixed(2) || 'N/A'}
- ROE: ${(analysisData?.fundamental_metrics?.roe * 100)?.toFixed(1) || 'N/A'}%
- Debt-to-Equity: ${analysisData?.fundamental_metrics?.debt_to_equity?.toFixed(2) || 'N/A'}

Technical Indicators:
- RSI: ${analysisData?.technical_indicators?.rsi?.toFixed(1) || 'N/A'}
- Price vs 20-day SMA: ${analysisData?.technical_indicators?.price_trend > 0 ? 'Above' : 'Below' || 'N/A'}

Sentiment Analysis:
- News Count: ${analysisData?.sentiment_data?.news_count || 'N/A'} articles
- Sentiment Trend: ${analysisData?.sentiment_data?.sentiment_trend || 'N/A'}
  `

  if (insightType === 'COMPREHENSIVE') {
    return `${baseContext}

Please provide a comprehensive analysis in the following format:

EXECUTIVE SUMMARY: (2-3 sentences summarizing the investment thesis)

KEY STRENGTHS: (3-4 bullet points of positive factors)

KEY CONCERNS: (2-3 bullet points of risk factors)

MARKET OUTLOOK: (1-2 sentences on market conditions affecting this stock)

INVESTMENT RECOMMENDATION: (Clear recommendation with rationale)

Keep it professional, data-driven, and actionable. Limit response to 300 words.`
  }

  if (insightType === 'QUICK') {
    return `${baseContext}

Provide a concise 2-paragraph analysis:
1. Current situation and key metrics
2. Investment recommendation with key reasoning

Limit to 150 words total.`
  }

  if (insightType === 'RISK_FOCUSED') {
    return `${baseContext}

Focus on risk analysis:

RISK ASSESSMENT: (Primary risks facing this investment)
VOLATILITY FACTORS: (What could cause price swings)
RISK MITIGATION: (How to manage these risks)
OVERALL RISK RATING: (Justify the ${analysisData?.risk_level || 'MEDIUM'} risk level)

Limit to 200 words.`
  }

  return baseContext + '\nProvide a balanced analysis of this stock opportunity.'
}

function parseGeminiResponse(aiResponse: string, analysisData: any): any {
  // Parse the AI response into structured insights
  const insights = {
    executive_summary: extractSection(aiResponse, 'EXECUTIVE SUMMARY') || 
                      aiResponse.split('\n')[0] || 
                      `Analysis suggests ${analysisData?.recommendation?.toLowerCase() || 'mixed'} outlook for this stock.`,
    
    key_strengths: extractBulletPoints(aiResponse, 'KEY STRENGTHS') || [
      'Technical indicators show positive momentum',
      'Fundamental metrics within acceptable ranges'
    ],
    
    key_concerns: extractBulletPoints(aiResponse, 'KEY CONCERNS') || [
      'Market volatility may impact performance',
      'Sector-specific risks require monitoring'
    ],
    
    market_outlook: extractSection(aiResponse, 'MARKET OUTLOOK') || 
                   'Current market conditions present both opportunities and challenges.',
    
    investment_recommendation: extractSection(aiResponse, 'INVESTMENT RECOMMENDATION') || 
                              `Based on analysis, this stock receives a ${analysisData?.recommendation || 'HOLD'} rating.`,
    
    confidence_level: analysisData?.confidence || 75,
    risk_factors: extractRiskFactors(aiResponse),
    catalysts: extractCatalysts(aiResponse),
    full_analysis: aiResponse
  }

  return insights
}

function extractSection(text: string, sectionName: string): string | null {
  const regex = new RegExp(`${sectionName}:?\\s*([^\\n]*(?:\\n(?![A-Z][A-Z\\s]*:)[^\\n]*)*)`, 'i')
  const match = text.match(regex)
  return match ? match[1].trim() : null
}

function extractBulletPoints(text: string, sectionName: string): string[] {
  const section = extractSection(text, sectionName)
  if (!section) return []
  
  return section
    .split('\n')
    .filter(line => line.trim().startsWith('•') || line.trim().startsWith('-') || line.trim().startsWith('*'))
    .map(line => line.replace(/^[\s•\-*]+/, '').trim())
    .filter(line => line.length > 0)
}

function extractRiskFactors(text: string): string[] {
  const riskSection = extractSection(text, 'RISK ASSESSMENT') || 
                     extractSection(text, 'KEY CONCERNS') || 
                     extractSection(text, 'VOLATILITY FACTORS')
  
  if (!riskSection) return ['Market volatility', 'Sector risks']
  
  return riskSection
    .split(/[.!]/)
    .map(s => s.trim())
    .filter(s => s.length > 10)
    .slice(0, 3)
}

function extractCatalysts(text: string): string[] {
  const catalystSection = extractSection(text, 'KEY STRENGTHS') || 
                         extractSection(text, 'POSITIVE FACTORS')
  
  if (!catalystSection) return ['Positive technical momentum']
  
  return catalystSection
    .split(/[.!]/)
    .map(s => s.trim())
    .filter(s => s.length > 10)
    .slice(0, 2)
}

function generateFallbackInsights(symbol: string, analysisData: any): any {
  const recommendation = analysisData?.recommendation || 'HOLD'
  const score = analysisData?.aggregate_score || 50
  
  return {
    executive_summary: `${symbol} shows ${score >= 60 ? 'positive' : score >= 40 ? 'mixed' : 'challenging'} signals across fundamental, technical, and sentiment analysis, warranting a ${recommendation} recommendation.`,
    
    key_strengths: [
      'Quantitative analysis shows measurable opportunities',
      'Technical indicators provide clear directional signals',
      'Risk-adjusted metrics support investment thesis'
    ],
    
    key_concerns: [
      'Market volatility may impact short-term performance',
      'Macro economic factors require ongoing monitoring',
      'Sector dynamics could influence stock trajectory'
    ],
    
    market_outlook: 'Current market conditions present both opportunities and challenges for equity investments.',
    
    investment_recommendation: `Based on comprehensive analysis yielding a score of ${score}/100, ${symbol} receives a ${recommendation} rating with ${analysisData?.confidence || 75}% confidence.`,
    
    confidence_level: analysisData?.confidence || 75,
    risk_factors: ['Market volatility', 'Sector-specific risks', 'Economic uncertainty'],
    catalysts: ['Technical momentum', 'Fundamental strength'],
    full_analysis: 'Fallback analysis generated due to AI service unavailability. This provides basic insights based on quantitative analysis.',
    source: 'fallback'
  }
}