// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egiiqbgumgltatfljbcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnaWlxYmd1bWdsdGF0ZmxqYmNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMzg2NjUsImV4cCI6MjA2MjgxNDY2NX0.ECaOGNSTRN5kWE4BImOPlfBemrmofzLR_wVFzH71j9o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);