// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlirkqmsjnlwbsfzzfjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsaXJrcW1zam5sd2JzZnp6ZmpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5ODMxMzIsImV4cCI6MjA3NDU1OTEzMn0.KTKXJWyRvJEjHRyibyI4-w3GulIIkfAcl1gH0VIwX2M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});